/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  BlizzardProfileData,
  BlizzardCharacterSummary,
  BlizzardGearItem,
  BlizzardCollectionMount,
  BlizzardCollectionPet,
  BlizzardReputation,
  AdventureJournalData,
  AdventureBossEntry,
  AdventureCompanionEntry,
  AdventureExplorationEntry,
  BlizzardQuestLog,
  BlizzardSpellbook,
} from "../types";
import * as pako from "pako";
import * as luaparse from "luaparse";
import { getWoWClassIcon, getWoWRaceIcon, getWoWFactionIcon } from "./blizzardIcons";
import { resolveDisplayIdForArmoryItem } from "./wowIdDatabase";

export interface ParsedAddonResult {
  activeProfile: BlizzardProfileData;
  allCharacters: BlizzardCharacterSummary[];
  detectedVersion: string;
  detectedVersionLabel: string;
  isForever: boolean;
  ruleset?: string;
  rawPayload?: any;
  worldBosses?: Record<string, any>;
  pendingChangesCount?: number;
  sessionStats?: any;
}

/**
 * Safely evaluates AST nodes generated by luaparse into standard JavaScript data
 */
function evaluateLuaAstNode(node: any): any {
  if (!node) return null;
  switch (node.type) {
    case "StringLiteral": {
      if (typeof node.value === "string" && node.value !== "") return node.value;
      if (typeof node.raw === "string") {
        const r = node.raw;
        if ((r.startsWith('"') && r.endsWith('"')) || (r.startsWith("'") && r.endsWith("'"))) {
          try {
            return JSON.parse(r);
          } catch (_) {
            return r.slice(1, -1);
          }
        }
        return r;
      }
      return node.value || "";
    }
    case "NumericLiteral":
      return node.value;
    case "BooleanLiteral":
      return node.value;
    case "NilLiteral":
      return null;
    case "Identifier":
      return node.name;
    case "TableConstructorExpression": {
      let isArray = true;
      let maxIdx = 0;
      let count = 0;
      const elements: any[] = [];
      const obj: Record<string, any> = {};

      for (let i = 0; i < node.fields.length; i++) {
        const field = node.fields[i];
        if (field.type === "TableValue") {
          count++;
          elements.push(evaluateLuaAstNode(field.value));
        } else if (field.type === "TableKey" || field.type === "TableKeyString") {
          let key: any;
          if (field.type === "TableKeyString") {
            key = field.key.name;
            isArray = false;
          } else {
            const evaluatedKey = evaluateLuaAstNode(field.key);
            key = evaluatedKey;
            if (typeof evaluatedKey === "number" && Number.isInteger(evaluatedKey) && evaluatedKey >= 1) {
              if (evaluatedKey > maxIdx) maxIdx = evaluatedKey;
              count++;
            } else {
              isArray = false;
            }
          }
          obj[String(key)] = evaluateLuaAstNode(field.value);
        }
      }

      if (isArray && elements.length > 0 && Object.keys(obj).length === 0) {
        return elements;
      }
      if (isArray && count > 0 && maxIdx === count && Object.keys(obj).length === count) {
        const arr: any[] = [];
        for (let i = 1; i <= count; i++) {
          arr.push(obj[String(i)]);
        }
        return arr;
      }
      return obj;
    }
    case "UnaryExpression": {
      if (node.operator === "-") {
        const val = evaluateLuaAstNode(node.argument);
        return typeof val === "number" ? -val : val;
      }
      if (node.operator === "not") {
        return !evaluateLuaAstNode(node.argument);
      }
      return evaluateLuaAstNode(node.argument);
    }
    default:
      return null;
  }
}

/**
 * Parses Lua code using luaparse into a clean JavaScript object
 */
function parseLuaStringToJs(code: string): Record<string, any> {
  const parseFn = (luaparse as any).parse || (luaparse as any).default?.parse;
  if (!parseFn) {
    throw new Error("luaparse não está disponível no ambiente.");
  }
  const ast = parseFn(code, { comments: false, scope: false, locations: false });
  const result: Record<string, any> = {};

  for (const statement of ast.body) {
    if (statement.type === "AssignmentStatement") {
      for (let i = 0; i < statement.variables.length; i++) {
        const varNode = statement.variables[i];
        const initNode = statement.init[i];
        if (varNode && (varNode.type === "Identifier" || varNode.name)) {
          result[varNode.name] = evaluateLuaAstNode(initNode);
        }
      }
    }
  }
  return result;
}

/**
 * Converts Lua SavedVariables table string to a JSON-compatible string (fallback regex)
 */
function convertLuaToJson(luaStr: string): string {
  let clean = luaStr
    .replace(/--\[\[[\s\S]*?\]\]--/g, "")
    .replace(/--.*$/gm, "")
    .trim();

  const match = clean.match(/(?:HaleckAccountImporterForeverDB|HaleckAccountImporterDB|HaloWoWExporterDB|MyCharDataDB)\s*=\s*(\{[\s\S]*\})/);
  if (match && match[1]) {
    clean = match[1];
  }

  clean = clean.replace(/\[\s*"([^"]+)"\s*\]\s*=/g, '"$1":');
  clean = clean.replace(/\[\s*([0-9]+)\s*\]\s*=/g, '"$1":');
  clean = clean.replace(/([a-zA-Z_][a-zA-Z0-9_]*)\s*=/g, '"$1":');
  clean = clean.replace(/:\s*nil\b/g, ": null");
  clean = clean.replace(/,\s*([}\]])/g, "$1");

  return clean;
}

/**
 * Parses raw text (JSON or Lua SavedVariables) from Addon into a structured ParsedAddonResult
 */
export function parseAddonData(input: string | any): ParsedAddonResult {
  let root: any = null;

  if (typeof input === "object" && input !== null) {
    root = input;
  } else if (typeof input === "string") {
    let trimmed = input.trim();

    // Suporte para payload exportado do Haleck Account Importer Forever (HAIF)
    if (trimmed.startsWith("HAIF_DATA:")) {
      trimmed = trimmed.replace(/^HAIF_DATA:/, "").trim();
    }

    // Suporte Canônico para LibDeflate Base64 (!HAI4:DEF: ou !HAI:DEF: ou !HAI:)
    if (trimmed.startsWith("!HAI4:DEF:") || trimmed.startsWith("!HAI:DEF:") || trimmed.startsWith("!HAI:")) {
      try {
        const b64Part = trimmed.replace(/^!HAI[0-9]*:DEF:/, "").replace(/^!HAI[0-9]*:/, "").trim();
        const binaryStr = typeof atob !== "undefined" ? atob(b64Part) : Buffer.from(b64Part, "base64").toString("binary");
        const bytes = new Uint8Array(binaryStr.length);
        for (let i = 0; i < binaryStr.length; i++) {
          bytes[i] = binaryStr.charCodeAt(i);
        }
        let decompressedText = "";
        try {
          decompressedText = new TextDecoder().decode(pako.inflateRaw(bytes));
        } catch (_) {
          decompressedText = new TextDecoder().decode(pako.inflate(bytes));
        }
        if (decompressedText) {
          trimmed = decompressedText.trim();
        }
      } catch (err: any) {
        console.warn("[LibDeflate Parser] Aviso ao descompactar payload Base64:", err?.message);
      }
    }

    // 1. Tentar primeiro parse direto como JSON
    if (trimmed.startsWith("{") || trimmed.startsWith("[")) {
      try {
        root = JSON.parse(trimmed);
      } catch (_) {}
    }

    // 2. Tentar parser robusto via luaparse para arquivos SavedVariables (.lua)
    if (!root) {
      try {
        const luaJs = parseLuaStringToJs(trimmed);
        const dbObj =
          luaJs.HaleckAccountImporterForeverDB ||
          luaJs.HaleckAccountImporterDB ||
          luaJs.HaloWoWExporterDB ||
          luaJs.HaleckAccountImporterForeverCharDB ||
          luaJs.HaleckAccountImporterCharDB ||
          luaJs.MyCharDataDB ||
          luaJs;
        if (dbObj && typeof dbObj === "object" && Object.keys(dbObj).length > 0) {
          root = dbObj;
        }
      } catch (err: any) {
        console.warn("[Lua AST Parser] Tentando fallbacks alternativos:", err?.message);
      }
    }

    // 3. Fallback de conversão regex para JSON se necessário
    if (!root) {
      try {
        const jsonStr = convertLuaToJson(trimmed);
        root = JSON.parse(jsonStr);
      } catch (_) {
        const objMatch = trimmed.match(/\{[\s\S]*\}/);
        if (objMatch) {
          try {
            root = JSON.parse(convertLuaToJson(objMatch[0]));
          } catch (e2) {
            throw new Error("Não foi possível processar o formato dos dados. Verifique se o conteúdo do arquivo Lua ou JSON está completo.");
          }
        } else {
          throw new Error("Formato não reconhecido. Cole o conteúdo de HaleckAccountImporter.lua ou o JSON exportado.");
        }
      }
    }
  }

  if (!root) {
    throw new Error("Dados vazios ou inválidos recebidos do Addon.");
  }

  // Extract inner snapshot if wrapped in lastExport or payload
  let snapshot = root.lastExport || root.payload || root.snapshot;

  // Se root contiver múltiplos personagens em .characters e lastExport não estiver presente
  if (!snapshot || !snapshot.character) {
    if (root.characters && typeof root.characters === "object") {
      const charKeys = Object.keys(root.characters);
      if (charKeys.length > 0) {
        // Tentar encontrar o último personagem ativo (latestCharacter)
        const activeKey = root.latestCharacter
          ? charKeys.find((k) => k.toLowerCase().includes(root.latestCharacter.toLowerCase()))
          : charKeys[0];
        snapshot = root.characters[activeKey || charKeys[0]];
      }
    }
  }

  if (!snapshot) {
    snapshot = root;
  }

  const char = snapshot.character || snapshot;
  const game = snapshot.game || {};

  const name = char.name || char.characterName || root.latestCharacter || "Personagem Importado";
  const realm = char.realm || char.realmName || game.realm || root.latestRealm || "WoW Forever Beta";
  const realmSlug = char.realmSlug || realm.toLowerCase().replace(/['\s]+/g, "-");
  const ruleset = char.ruleset || game.ruleset || root.ruleset || (realm.toLowerCase().includes("forever") ? realm : undefined);

  // Version detection
  let detectedVersion = (game.version || char.wow_version || "").toLowerCase();
  const rawPath = String(game.clientFolder || game.folder || game.path || char.folder || "").toLowerCase();
  let isForever = false;

  // CRITICAL DISTINCTION:
  // The WoW Forever Beta client resides strictly in `_classic_beta_` on disk.
  // It is NOT Classic Era (`_classic_era_`) nor Classic Progression (`_classic_`).
  // When WoW Forever launches on Nov 4, 2026, the official folder name will be announced by Blizzard.
  if (
    rawPath.includes("_classic_beta_") ||
    rawPath.includes("classic_beta") ||
    game.isForever ||
    game.isForeverBeta ||
    char.isForever ||
    root.addon === "HaleckAccountImporterForever" ||
    root.clientBuild === "16001" ||
    detectedVersion.includes("forever") ||
    realm.toLowerCase().includes("forever") ||
    realm.toLowerCase().includes("16001") ||
    String(game.build || "").startsWith("1600")
  ) {
    detectedVersion = "forever";
    isForever = true;
  } else if (
    rawPath.includes("_classic_era_") ||
    detectedVersion.includes("era") ||
    detectedVersion === "classic"
  ) {
    detectedVersion = "classic";
  } else if (rawPath.includes("_classic_") || detectedVersion.includes("mop") || detectedVersion.includes("pandaria")) {
    detectedVersion = "mop";
  } else if (detectedVersion.includes("tbc") || detectedVersion.includes("crusade")) {
    detectedVersion = "tbc";
  } else {
    detectedVersion = "retail";
  }

  const versionLabels: Record<string, string> = {
    retail: "WoW Retail (The War Within)",
    classic: "WoW Classic Era (1.15.x)",
    forever: "WoW Forever (Build 16001 • _classic_beta_)",
    mop: "Mists of Pandaria",
    tbc: "The Burning Crusade",
  };
  const detectedVersionLabel = versionLabels[detectedVersion] || "World of Warcraft";

  const charClass = char.characterClass || char.class || "Warrior";
  const charRace = char.race || "Orc";
  const charGender = (char.gender || "MALE").toUpperCase();
  const charFaction = (char.faction || "HORDE").toUpperCase();
  const charLevel = Number(char.level) || 80;
  const equippedItemLevel = Number(char.equippedItemLevel || char.itemLevel || char.averageItemLvl) || 0;
  const averageItemLevel = Number(char.averageItemLevel || char.averageItemLvl || equippedItemLevel) || equippedItemLevel;
  const achievementPoints = Number(char.achievementPoints ?? snapshot.achievementPoints) || 0;

  // Process equipped items (supports Array or Record<slotName, itemObj>)
  const rawEquipped = snapshot.equippedItems || snapshot.gear || char.gear || [];
  const equippedItems: BlizzardGearItem[] = [];
  const gearList: any[] = Array.isArray(rawEquipped)
    ? rawEquipped
    : rawEquipped && typeof rawEquipped === "object"
    ? Object.values(rawEquipped)
    : [];

  for (const item of gearList) {
    if (item && (item.id || item.itemId || item.itemID)) {
      const itemId = Number(item.itemId || item.itemID || item.id);
      const slot = item.slot || item.slotName || "UNKNOWN";
      const displayId = Number(item.displayId || item.itemDisplayId) || resolveDisplayIdForArmoryItem({
        id: itemId,
        itemId: itemId,
        slot: slot,
        slotId: item.slotId || item.slotID,
        displayId: item.displayId || item.itemDisplayId,
        transmog: item.transmog,
      });

      equippedItems.push({
        id: itemId,
        itemId: itemId,
        displayId: displayId,
        slot: slot,
        name: item.name || `Item #${itemId}`,
        quality: String(item.quality || "EPIC").toUpperCase(),
        itemLevel: Number(item.itemLevel || item.ilvl) || equippedItemLevel,
        iconUrl: item.iconUrl || item.icon || "",
        inventoryType: item.itemType || item.inventoryType || "Armor",
        transmog: item.transmog,
        enchantment: item.enchantment || (item.enchantID ? `Encanto #${item.enchantID}` : undefined),
        stats: Array.isArray(item.stats) ? item.stats : [],
      });
    }
  }

  // Process inventory & bags (supports HAIF bags structure 0-4)
  let inventory = snapshot.inventory;
  const rawBags = snapshot.bags || char.bags;
  if (!inventory && rawBags) {
    const bagsList = Array.isArray(rawBags) ? rawBags : Object.values(rawBags);
    const backpackBag = bagsList.find((b: any) => b && (b.bagID === 0 || b.id === 0));
    const extraBags = bagsList.filter((b: any) => b && (b.bagID > 0 || (b.id > 0 && b.id <= 4)));

    const mapBagItems = (bag: any) => {
      if (!bag || !bag.items) return [];
      const itemsList = Array.isArray(bag.items) ? bag.items : Object.values(bag.items);
      return itemsList.filter((it: any) => it && (it.itemID || it.itemId || it.id)).map((it: any) => ({
        id: Number(it.itemID || it.itemId || it.id),
        name: it.name || `Item #${it.itemID || it.id}`,
        iconUrl: it.icon || it.iconUrl || "",
        quality: String(it.quality || "COMMON").toUpperCase(),
        count: Number(it.count || 1),
        slotIndex: Number(it.slot || 0),
      }));
    };

    const goldTotal = Number(char.money || 0);
    inventory = {
      backpack: {
        id: 0,
        name: "Mochila",
        iconUrl: "https://wow.zamimg.com/images/wow/icons/large/inv_misc_bag_08.jpg",
        slotCount: backpackBag?.numSlots || 16,
        bagSlotIndex: 0,
        items: mapBagItems(backpackBag),
      },
      bags: extraBags.map((b: any, idx: number) => ({
        id: b.bagID || idx + 1,
        name: b.name || `Bolsa ${idx + 1}`,
        iconUrl: "https://wow.zamimg.com/images/wow/icons/large/inv_misc_bag_08.jpg",
        slotCount: b.numSlots || 16,
        bagSlotIndex: idx + 1,
        items: mapBagItems(b),
      })),
      currencies: [],
      gold: Math.floor(goldTotal / 10000),
      silver: Math.floor((goldTotal % 10000) / 100),
      copper: goldTotal % 100,
    };
  } else if (!inventory) {
    const goldTotal = Number(char.money || 0);
    inventory = {
      backpack: { id: 0, name: "Backpack", iconUrl: "", slotCount: 16, bagSlotIndex: 0, items: [] },
      bags: [],
      currencies: [],
      gold: Math.floor(goldTotal / 10000),
      silver: Math.floor((goldTotal % 10000) / 100),
      copper: goldTotal % 100,
    };
  }

  // Process collections (mounts, pets, titles)
  const collectionsMounts: BlizzardCollectionMount[] = [];
  const rawMounts = snapshot.collections?.mounts || snapshot.mounts || char.mounts || [];
  const mountsList = Array.isArray(rawMounts) ? rawMounts : Object.values(rawMounts);
  for (const m of mountsList) {
    if (m && (m.id || m.name || m.spellID || m.spellId)) {
      collectionsMounts.push({
        id: Number(m.id || m.spellID || m.spellId || Date.now()),
        name: m.name || "Mount",
        iconUrl: m.iconUrl || m.icon || "",
        spellId: m.spellID || m.spellId ? Number(m.spellID || m.spellId) : undefined,
        itemId: m.itemId ? Number(m.itemId) : undefined,
        mountType: m.mountType || "ground",
        source: m.source || "HAIF Sync",
        description: m.description || "",
        isCollected: true,
      });
    }
  }

  const collectionsPets: BlizzardCollectionPet[] = [];
  const rawPets = snapshot.collections?.pets || snapshot.pets || char.pets || [];
  const petsList = Array.isArray(rawPets) ? rawPets : Object.values(rawPets);
  for (const p of petsList) {
    if (p && (p.id || p.speciesId || p.speciesID || p.name)) {
      collectionsPets.push({
        id: Number(p.id || p.speciesId || p.speciesID || Date.now()),
        speciesId: Number(p.speciesId || p.speciesID || p.id || 0),
        name: p.name || "Pet",
        iconUrl: p.iconUrl || p.icon || "",
        family: p.family || "Beast",
        level: Number(p.level) || 1,
        quality: String(p.quality || "RARE").toUpperCase(),
        source: p.source || "HAIF Sync",
        isCollected: true,
        isFavorite: !!p.isFavorite,
      });
    }
  }

  // Process reputations (supports Array or Record)
  const rawReps = snapshot.reputations || char.reputations || [];
  const parsedReputations: BlizzardReputation[] = [];
  const repsList = Array.isArray(rawReps) ? rawReps : typeof rawReps === "object" ? Object.values(rawReps) : [];
  if (repsList.length > 0) {
    const standingPtBRMap: Record<string, string> = {
      Exalted: "Exaltado",
      Revered: "Reverenciado",
      Honored: "Honrado",
      Friendly: "Respeitado",
      Neutral: "Neutro",
      Unfriendly: "Inamistoso",
      Hostile: "Hostil",
      Hated: "Odiado",
    };
    const tierColorMap: Record<string, string> = {
      Exalted: "text-cyan-400 bg-cyan-950/80 border-cyan-500/40",
      Revered: "text-blue-400 bg-blue-950/80 border-blue-500/40",
      Honored: "text-emerald-400 bg-emerald-950/80 border-emerald-500/40",
      Friendly: "text-green-400 bg-green-950/80 border-green-500/40",
      Neutral: "text-amber-400 bg-amber-950/80 border-amber-500/40",
      Unfriendly: "text-orange-400 bg-orange-950/80 border-orange-500/40",
      Hostile: "text-red-400 bg-red-950/80 border-red-500/40",
      Hated: "text-rose-500 bg-rose-950/80 border-rose-500/40",
    };
    for (const r of repsList) {
      if (r && (r.factionName || r.name)) {
        const repName = r.factionName || r.name;
        const standing = r.standingLabel || r.standing || "Neutral";
        const current = Number(r.value ?? r.current ?? 0);
        const max = Number(r.max ?? 1) || 1;
        const percent = Math.min(100, Math.max(0, Math.round((current / max) * 100)));
        parsedReputations.push({
          id: Number(r.factionId || r.id || Date.now() + Math.random()),
          name: repName,
          standing,
          standingPtBR: standingPtBRMap[standing] || standing,
          current,
          max,
          percent,
          tierColor: tierColorMap[standing] || "text-zinc-400 bg-zinc-900 border-zinc-800",
          category: r.category || (detectedVersion === "retail" ? "The War Within" : "Azeroth (WoW Forever)"),
        });
      }
    }
  }

  // Process professions (supports HAIF skills breakdown)
  const rawProfessions = snapshot.professions || char.skills?.professions || { primary: [], secondary: [] };
  let primaryProfs: any[] = [];
  let secondaryProfs: any[] = [];
  if (Array.isArray(rawProfessions)) {
    primaryProfs = rawProfessions.filter((p: any) => p.category === "Profissões" || p.category === "Professions" || !p.category);
    secondaryProfs = rawProfessions.filter((p: any) => p.category === "Profissões Secundárias" || p.category === "Secondary Professions");
  } else if (rawProfessions && typeof rawProfessions === "object") {
    primaryProfs = Array.isArray(rawProfessions.primary) ? rawProfessions.primary : [];
    secondaryProfs = Array.isArray(rawProfessions.secondary) ? rawProfessions.secondary : [];
  }
  const professions = {
    primary: primaryProfs.map((p: any) => ({
      name: p.name,
      skillLevel: p.rank || p.skillLevel || 300,
      maxSkillLevel: p.maxRank || p.maxSkillLevel || 300,
    })),
    secondary: secondaryProfs.map((p: any) => ({
      name: p.name,
      skillLevel: p.rank || p.skillLevel || 300,
      maxSkillLevel: p.maxRank || p.maxSkillLevel || 300,
    })),
  };

  // Process PvP
  const rawPvp = snapshot.pvp || char.pvp || {};
  const pvp = {
    lifetimeHK: Number(rawPvp.lifetimeHK || rawPvp.honorableKills || 0),
    honorPoints: Number(rawPvp.honorPoints || 0),
    rankName: rawPvp.rankName || (charLevel >= 60 ? "Centurion" : "Soldier"),
    rankNumber: Number(rawPvp.rankNumber || 0),
    arenaRating: Number(rawPvp.arenaRating || 0),
  };

  // Process Lockouts
  const rawLockouts = snapshot.lockouts || char.lockouts || [];
  const lockouts = Array.isArray(rawLockouts) ? rawLockouts : [];

  // Process Quests (supports HAIF completedQuests dictionary or array)
  const rawQuests = snapshot.quests || {};
  let completedQuestIds: number[] = [];
  if (char.completedQuests) {
    if (Array.isArray(char.completedQuests)) {
      completedQuestIds = char.completedQuests.map(Number);
    } else if (typeof char.completedQuests === "object") {
      completedQuestIds = Object.keys(char.completedQuests).map(Number).filter((n) => !isNaN(n) && n > 0);
    }
  } else if (Array.isArray(rawQuests.completedQuests)) {
    completedQuestIds = rawQuests.completedQuests.map(Number);
  }

  const activeQuestsList = Array.isArray(char.activeQuests)
    ? char.activeQuests
    : Array.isArray(rawQuests.activeQuests)
    ? rawQuests.activeQuests
    : [];

  const parsedQuests: BlizzardQuestLog = {
    completedCount: completedQuestIds.length > 0 ? completedQuestIds.length : Number(rawQuests.completedCount || 0),
    completedQuests: completedQuestIds,
    activeQuests: activeQuestsList.map((q: any) => ({
      id: Number(q.questID || q.id || 0),
      title: String(q.title || "Missão"),
      level: Number(q.level || 1),
      isComplete: !!q.isComplete,
      isFailed: !!q.isFailed,
      zone: q.zone || "Azeroth",
    })),
  };

  // Process Spells & Flight Paths (ATT-grade)
  const rawSpells = snapshot.spells || {};
  const flightPathsCount = char.flightPaths
    ? Object.keys(char.flightPaths).length
    : Number(rawSpells.flightPathsCount || (Array.isArray(rawSpells.flightPaths) ? rawSpells.flightPaths.length : 0));

  const parsedSpells: BlizzardSpellbook = {
    totalSpells: Number(rawSpells.totalSpells || (Array.isArray(rawSpells.spells) ? rawSpells.spells.length : 0)),
    spells: Array.isArray(rawSpells.spells) ? rawSpells.spells.map((s: any) => ({
      id: Number(s.id || 0),
      name: String(s.name || "Habilidade"),
      rank: s.rank || "",
      icon: s.icon || "",
      tab: s.tab || "Geral",
      isPassive: !!s.isPassive,
    })) : [],
    flightPathsCount,
  };

  // Process Adventure Journal ("Meu Diário de Aventura")
  const rawJournal = snapshot.adventureJournal || {};
  const rawTimeline = Array.isArray(rawJournal.timeline) ? rawJournal.timeline : [];
  const rawBosses = rawJournal.bosses || {};
  const rawComps = rawJournal.companions || {};
  const rawExp = rawJournal.exploration || {};
  const rawDeaths = Array.isArray(rawJournal.deaths) ? rawJournal.deaths : [];
  const rawJournalStats = rawJournal.statistics || snapshot.stepCounter || {};

  const bossesList: AdventureBossEntry[] = Array.isArray(rawBosses)
    ? rawBosses
    : Object.values(rawBosses).map((b: any) => ({
        id: b.id || b.name,
        name: b.name || "Chefe",
        firstKillDate: b.firstKillDate || "",
        killCount: Number(b.killCount || 1),
        zone: b.zone || "",
        level: Number(b.level || 1),
        isWorldBoss: !!b.isWorldBoss,
      }));

  const companionsList: AdventureCompanionEntry[] = Array.isArray(rawComps)
    ? rawComps
    : Object.values(rawComps).map((c: any) => ({
        name: c.name || "Aventureiro",
        realm: c.realm || realm,
        class: c.class || "Warrior",
        level: Number(c.level || 1),
        firstMetDate: c.firstMetDate || "",
        lastMetDate: c.lastMetDate || "",
        zone: c.zone || "",
        timesGrouped: Number(c.timesGrouped || 1),
      }));

  const explorationList: AdventureExplorationEntry[] = Array.isArray(rawExp)
    ? rawExp
    : Object.values(rawExp).map((e: any) => ({
        zone: e.zone || "Azeroth",
        firstVisited: e.firstVisited || "",
        visitCount: Number(e.visitCount || 1),
      }));

  const parsedAdventureJournal: AdventureJournalData = {
    timeline: rawTimeline.map((t: any) => ({
      id: String(t.id || Date.now()),
      timestamp: t.timestamp || "",
      type: t.type || "milestone",
      title: t.title || "Marco da Jornada",
      desc: t.desc || "",
      icon: t.icon || "",
      zone: t.zone || "",
      level: Number(t.level || 1),
      details: t.details || undefined,
    })),
    bosses: bossesList,
    companions: companionsList,
    exploration: explorationList,
    deaths: rawDeaths.map((d: any) => ({
      id: String(d.id || Date.now()),
      timestamp: d.timestamp || "",
      killerName: d.killerName || "Inimigo",
      zone: d.zone || "",
      subZone: d.subZone || "",
      coordinates: d.coordinates || "",
      level: Number(d.level || 1),
      lastWords: d.lastWords || "",
    })),
    statistics: { ...rawJournalStats, ...(snapshot.nativeStatistics || {}) },
    steps: Number(rawJournalStats.steps || snapshot.stepCounter?.steps || 0),
    distanceYards: Number(rawJournalStats.distanceYards || snapshot.stepCounter?.distanceYards || 0),
    totalQuestsCompleted: parsedQuests.completedCount,
    totalBossesDefeated: bossesList.length,
    totalCompanionsMet: companionsList.length,
  };

  // Process World Bosses (Vanilla+ & WoW Forever)
  const rawWorldBosses = snapshot.worldBosses || root.worldBosses || {};
  let formattedWorldBosses: BlizzardProfileData["worldBosses"] = [];
  if (Array.isArray(rawWorldBosses)) {
    formattedWorldBosses = rawWorldBosses;
  } else if (rawWorldBosses && typeof rawWorldBosses === "object") {
    for (const [key, b] of Object.entries(rawWorldBosses)) {
      if (b && typeof b === "object") {
        const bObj = b as any;
        const statusMap: Record<string, "Available" | "Defeated" | "Spawning Soon"> = {
          active: "Available",
          spawned: "Available",
          killed: "Defeated",
        };
        formattedWorldBosses.push({
          name: bObj.name || key,
          zone: bObj.zone || "Azeroth",
          status: statusMap[bObj.status] || "Spawning Soon",
          lastKilled: bObj.killedAt,
          respawnEstimate: bObj.respawnMinDate ? `Janela: ${bObj.respawnMinDate}` : undefined,
          bossId: bObj.id,
          respawnMinEpoch: bObj.respawnMinEpoch,
          respawnMaxEpoch: bObj.respawnMaxEpoch,
          iconUrl: key.includes("azuregos")
            ? "https://wow.zamimg.com/images/wow/icons/large/spell_frost_glacier.jpg"
            : key.includes("kazzak")
            ? "https://wow.zamimg.com/images/wow/icons/large/spell_shadow_summoninfernal.jpg"
            : "https://wow.zamimg.com/images/wow/icons/large/spell_nature_abolishpoison.jpg",
        });
      }
    }
  }

  // Build character summary entry
  const summary: BlizzardCharacterSummary = {
    id: Date.now(),
    name,
    realm,
    realmSlug,
    ruleset,
    level: charLevel,
    characterClass: charClass,
    race: charRace,
    faction: charFaction,
    gender: charGender,
    equippedItemLevel,
    averageItemLevel,
    activeSpec: char.activeSpec || "Primary Spec",
    achievementPoints,
    gameMode: detectedVersion,
    wow_version: detectedVersion,
    guild: char.guild,
    classIconUrl: getWoWClassIcon(charClass),
    raceIconUrl: getWoWRaceIcon(charRace, charGender),
    factionIconUrl: getWoWFactionIcon(charFaction),
    avatarUrl: getWoWRaceIcon(charRace, charGender),
  };

  const activeProfile: BlizzardProfileData = {
    name,
    realm,
    realmSlug,
    ruleset,
    level: charLevel,
    characterClass: charClass,
    race: charRace,
    gender: charGender,
    faction: charFaction,
    equippedItemLevel,
    averageItemLevel,
    activeSpec: char.talents?.specString || char.activeSpec || "31/20/0",
    achievementPoints,
    achievementPointsTotal: achievementPoints,
    guild: char.guild,
    gameMode: detectedVersion,
    wow_version: detectedVersion,
    classIconUrl: getWoWClassIcon(charClass),
    raceIconUrl: getWoWRaceIcon(charRace, charGender),
    factionIconUrl: getWoWFactionIcon(charFaction),
    avatarUrl: getWoWRaceIcon(charRace, charGender),
    equippedItems,
    inventory,
    collections: {
      mounts: collectionsMounts,
      pets: collectionsPets,
      toys: snapshot.collections?.toys || [],
      titles: snapshot.collections?.titles || char.titles || [],
      totalMountsCount: collectionsMounts.length,
      totalPetsCount: collectionsPets.length,
      totalToysCount: (snapshot.collections?.toys || []).length,
    },
    achievements: snapshot.achievements || [],
    reputations: parsedReputations.length > 0 ? parsedReputations : (snapshot.reputations || []),
    professions,
    pvp,
    lockouts,
    hardcore: snapshot.hardcore || char.hardcore || { isDead: false, survivalStatus: "Alive" },
    hardcoreDeathCertificate: (snapshot.hardcore || char.hardcore)?.deathCertificate,
    bank: (function() {
      const rawBank = snapshot.bank || char.bank;
      if (!rawBank) {
        return { mainBank: [], reagentBank: [], warbandBank: [], lastBankVisit: undefined };
      }
      if (Array.isArray(rawBank.mainBank)) return rawBank;
      const bankContainers = Array.isArray(rawBank) ? rawBank : Object.values(rawBank);
      const itemsList: any[] = [];
      for (const container of bankContainers) {
        if (container && container.items) {
          const cItems = Array.isArray(container.items) ? container.items : Object.values(container.items);
          for (const it of cItems) {
            if (it && (it.itemID || it.id || it.itemId)) {
              itemsList.push({
                id: Number(it.itemID || it.itemId || it.id),
                name: it.name || `Item #${it.itemID || it.id}`,
                iconUrl: it.icon || it.iconUrl || "",
                quality: String(it.quality || "COMMON").toUpperCase(),
                count: Number(it.count || 1),
              });
            }
          }
        }
      }
      return {
        mainBank: itemsList,
        reagentBank: [],
        warbandBank: [],
        lastBankVisit: char.bankLastScanned ? new Date(char.bankLastScanned * 1000).toISOString() : undefined,
      };
    })(),
    accountEconomy: {
      totalGold: Number(root.totalAccountGold || root.accountGold || snapshot.accountEconomy?.totalGold || char.money || 0),
      charactersGold: root.characters
        ? Object.values(root.characters).map((c: any) => ({
            characterName: c.name || "Alt",
            realm: c.realm || realm,
            gold: Math.floor(Number(c.money || 0) / 10000),
            faction: c.faction || "HORDE",
            class: c.class || "Warrior",
            level: Number(c.level) || 60,
          }))
        : [],
      sessionDeltaGold: snapshot.accountEconomy?.sessionDeltaGold || 0,
    },
    mythicPlus: snapshot.mythicPlus || {
      rating: 0,
      currentKeystone: undefined,
      runHistory: [],
      greatVault: [],
    },
    worldBosses: formattedWorldBosses,
    quests: parsedQuests,
    spells: parsedSpells,
    adventureJournal: parsedAdventureJournal,
    stats: (function() {
      const rawStats = snapshot.stats || char.stats;
      if (!rawStats) {
        return { health: charLevel <= 60 ? 5200 : 6400000, power: 100, armor: 8500 };
      }
      return {
        health: Number(rawStats.health || 5200),
        maxHealth: Number(rawStats.maxHealth || rawStats.health || 5200),
        power: Number(rawStats.power || 100),
        maxPower: Number(rawStats.maxPower || rawStats.power || 100),
        powerType: rawStats.powerType || "MANA",
        armor: Number(rawStats.armor?.effective ?? rawStats.armor ?? 8500),
        attributes: rawStats.attributes || {},
        melee: rawStats.melee || {},
        ranged: rawStats.ranged || {},
        defense: rawStats.defense || {},
        spell: rawStats.spell || {},
        resistances: rawStats.resistances || {},
      };
    })(),
  };

  // Handle multi-character history if available
  const allCharacters: BlizzardCharacterSummary[] = [summary];

  if (root.characters && typeof root.characters === "object") {
    for (const [key, cSnap] of Object.entries<any>(root.characters)) {
      if (cSnap && typeof cSnap === "object") {
        const cChar = cSnap.character || cSnap;
        const cName = cChar.name || cChar.characterName;
        const cRealm = cChar.realm || cChar.realmName || realm;
        if (cName && cName.toLowerCase() !== name.toLowerCase()) {
          const cClass = cChar.characterClass || cChar.class || "Warrior";
          const cRace = cChar.race || "Orc";
          const cGender = (cChar.gender || "MALE").toUpperCase();
          const cFaction = (cChar.faction || "HORDE").toUpperCase();
          const cLevel = Number(cChar.level) || 60;
          const cVer = (cSnap.game?.version || cChar.wow_version || detectedVersion).toLowerCase();

          allCharacters.push({
            id: Date.now() + Math.random(),
            name: cName,
            realm: cRealm,
            realmSlug: cChar.realmSlug || cRealm.toLowerCase().replace(/['\s]+/g, "-"),
            ruleset: cChar.ruleset || ruleset,
            level: cLevel,
            characterClass: cClass,
            race: cRace,
            faction: cFaction,
            gender: cGender,
            equippedItemLevel: Number(cChar.equippedItemLevel || cSnap.equippedItemLevel) || 0,
            averageItemLevel: Number(cChar.averageItemLevel || cSnap.averageItemLevel) || 0,
            activeSpec: cChar.activeSpec || "Primary Spec",
            achievementPoints: Number(cChar.achievementPoints || cSnap.achievementPoints) || 0,
            gameMode: cVer,
            wow_version: cVer,
            guild: cChar.guild,
            classIconUrl: getWoWClassIcon(cClass),
            raceIconUrl: getWoWRaceIcon(cRace, cGender),
            factionIconUrl: getWoWFactionIcon(cFaction),
            avatarUrl: getWoWRaceIcon(cRace, cGender),
          });
        }
      }
    }
  }

  return {
    activeProfile,
    allCharacters,
    detectedVersion,
    detectedVersionLabel,
    isForever,
    ruleset,
    rawPayload: snapshot,
    worldBosses: rawWorldBosses,
    pendingChangesCount: Number(snapshot.pendingChangesCount || root.pendingChanges?.length || 0),
    sessionStats: snapshot.sessionStats || root.sessionStats,
  };
}
