/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * Catálogo Oficial de Fontes DB2, APIs e Versões do World of Warcraft
 */

export interface WoWVersionDefinition {
  id: string;
  name: string;
  shortName: string;
  clientVersion: string;
  buildNumber: string;
  tocInterface: number;
  folderName: string;
  isPrimary: boolean;
  db2BuildUrl: string;
  db2BuildParam?: string;
  description: string;
  accentColor: string;
}

export interface WoWDb2SourceItem {
  id: string;
  category: string;
  idType: string;
  title: string;
  url: string;
  db2Table?: string;
  description: string;
  targetVersions: string[];
}

/**
 * Catálogo Canônico de Versões do World of Warcraft com Numeração Específica
 */
export const WOW_VERSIONS_CATALOG: WoWVersionDefinition[] = [
  {
    id: "forever",
    name: "WoW Forever (Vanilla+ Prioritário)",
    shortName: "WoW Forever",
    clientVersion: "1.60.1",
    buildNumber: "70009 / 16001",
    tocInterface: 160001,
    folderName: "_classic_beta_",
    isPrimary: true,
    db2BuildUrl: "https://wago.tools/db2?build=1.60.1.70009",
    db2BuildParam: "1.60.1.70009",
    description: "Versão canônica prioritária Vanilla+ com lançamento em 04 de Novembro de 2026. Pasta do cliente no disco é _classic_beta_.",
    accentColor: "#00f2fe",
  },
  {
    id: "classic_era",
    name: "WoW Classic Era (1.15.x)",
    shortName: "Classic Era",
    clientVersion: "1.15.6",
    buildNumber: "58238",
    tocInterface: 11506,
    folderName: "_classic_era_",
    isPrimary: false,
    db2BuildUrl: "https://wago.tools/db2?build=1.15.6.58238",
    db2BuildParam: "1.15.6.58238",
    description: "Servidores Classic Era puros de nível 60 com regras originais de 2004-2006.",
    accentColor: "#fbbf24",
  },
  {
    id: "tbc",
    name: "Classic The Burning Crusade (2.5.x)",
    shortName: "TBC Classic",
    clientVersion: "2.5.4",
    buildNumber: "44833",
    tocInterface: 20504,
    folderName: "_classic_",
    isPrimary: false,
    db2BuildUrl: "https://wago.tools/db2",
    description: "Expansão de Terralém (Outland), Ilha de Quel'Danas e raides de nível 70.",
    accentColor: "#10b981",
  },
  {
    id: "wotlk",
    name: "Classic Wrath of the Lich King (3.4.x)",
    shortName: "WotLK Classic",
    clientVersion: "3.4.3",
    buildNumber: "51699",
    tocInterface: 30403,
    folderName: "_classic_",
    isPrimary: false,
    db2BuildUrl: "https://wago.tools/db2",
    description: "Nortúndria (Northrend), Cavaleiros da Morte e Cidadela da Coroa de Gelo.",
    accentColor: "#38bdf8",
  },
  {
    id: "cata",
    name: "Classic Cataclysm (4.4.x)",
    shortName: "Cata Classic",
    clientVersion: "4.4.1",
    buildNumber: "57943",
    tocInterface: 40401,
    folderName: "_classic_",
    isPrimary: false,
    db2BuildUrl: "https://wago.tools/db2?build=4.4.1.57943",
    db2BuildParam: "4.4.1.57943",
    description: "Devastação de Azeroth por Asa da Morte, transfiguração clássica e nível 85.",
    accentColor: "#f97316",
  },
  {
    id: "mop",
    name: "Classic Mists of Pandaria (5.4.x)",
    shortName: "MoP Classic",
    clientVersion: "5.4.8",
    buildNumber: "18414",
    tocInterface: 50400,
    folderName: "_classic_",
    isPrimary: false,
    db2BuildUrl: "https://wago.tools/db2",
    description: "Continente de Pandária, classe Monge, batalhas de mascotes e raides nível 90.",
    accentColor: "#34d399",
  },
  {
    id: "wod",
    name: "Warlords of Draenor (6.2.x)",
    shortName: "WoD",
    clientVersion: "6.2.4",
    buildNumber: "21742",
    tocInterface: 60200,
    folderName: "_classic_",
    isPrimary: false,
    db2BuildUrl: "https://wago.tools/db2",
    description: "Draenor do passado, Guarnições (Garrisons), seguidores e Cidadela Fogo do Inferno.",
    accentColor: "#e11d48",
  },
  {
    id: "legion",
    name: "Legion (7.3.x)",
    shortName: "Legion",
    clientVersion: "7.3.5",
    buildNumber: "26972",
    tocInterface: 70300,
    folderName: "_classic_",
    isPrimary: false,
    db2BuildUrl: "https://wago.tools/db2",
    description: "Ilhas Partidas, Armas Artefato, Ordem de Classe, Caçadores de Demônios e Argus.",
    accentColor: "#84cc16",
  },
  {
    id: "bfa",
    name: "Battle for Azeroth (8.3.x)",
    shortName: "BfA",
    clientVersion: "8.3.7",
    buildNumber: "35662",
    tocInterface: 80300,
    folderName: "_classic_",
    isPrimary: false,
    db2BuildUrl: "https://wago.tools/db2",
    description: "Guerra Aliança x Horda em Kul Tiras e Zandalar, Coração de Azeroth e Visões de N'Zoth.",
    accentColor: "#a855f7",
  },
  {
    id: "shadowlands",
    name: "Shadowlands (9.2.x)",
    shortName: "Shadowlands",
    clientVersion: "9.2.7",
    buildNumber: "45745",
    tocInterface: 90207,
    folderName: "_retail_",
    isPrimary: false,
    db2BuildUrl: "https://wago.tools/db2",
    description: "Terras Sombrias, Pactos (Covenants), Thanator (Torghast) e Sepulcro dos Primogênitos.",
    accentColor: "#6366f1",
  },
  {
    id: "dragonflight",
    name: "Dragonflight (10.2.x)",
    shortName: "Dragonflight",
    clientVersion: "10.2.7",
    buildNumber: "55000",
    tocInterface: 100207,
    folderName: "_retail_",
    isPrimary: false,
    db2BuildUrl: "https://wago.tools/db2",
    description: "Ilhas do Dragão, Evocadores Dracthyr, Montaria Dragônica e árvore de talentos renovada.",
    accentColor: "#ec4899",
  },
  {
    id: "retail",
    name: "WoW Retail: The War Within (11.x)",
    shortName: "The War Within",
    clientVersion: "11.1.0",
    buildNumber: "59340",
    tocInterface: 110100,
    folderName: "_retail_",
    isPrimary: false,
    db2BuildUrl: "https://wago.tools/db2",
    description: "Versão atual do Retail. Cofre de Guerra (Warband), Profundezas (Delves) e Raides subterrâneas.",
    accentColor: "#8b5cf6",
  },
  {
    id: "midnight",
    name: "WoW Retail: Midnight (12.x / 12.1)",
    shortName: "Midnight (12.1)",
    clientVersion: "12.1.0",
    buildNumber: "62000+",
    tocInterface: 120100,
    folderName: "_retail_",
    isPrimary: false,
    db2BuildUrl: "https://wago.tools/db2",
    description: "Próxima expansão do Retail em Quel'Thalas, Void e Luz. Suporte antecipado a estruturas DB2 12.1.",
    accentColor: "#c084fc",
  },
];

/**
 * Catálogo Canônico de Todas as Fontes Oficiais DB2, APIs e Documentações
 */
export const WOW_DB2_SOURCES_CATALOG: WoWDb2SourceItem[] = [
  // 1. Arquitetura Global, FrameXML & Especificação TOC
  {
    id: "src_blizzard_game_data_api",
    category: "Arquitetura & API",
    idType: "Blizzard_REST_API",
    title: "Blizzard Battle.net WoW Game Data APIs",
    url: "https://community.developer.battle.net/documentation/world-of-warcraft/game-data-apis",
    description: "Documentação oficial das APIs REST da Blizzard para Game Data no WoW Retail (Itens, montarias, mascotes, feitiços, reinos e classes).",
    targetVersions: ["retail", "midnight", "forever"],
  },
  {
    id: "src_blizzard_profile_api",
    category: "Arquitetura & API",
    idType: "Blizzard_Profile_API",
    title: "Blizzard Battle.net WoW Profile APIs",
    url: "https://community.developer.battle.net/documentation/world-of-warcraft/profile-apis",
    description: "Documentação oficial das APIs REST de perfil no WoW Retail (Armory, equipamentos equipados, transmogs, conquistas, títulos e coleções).",
    targetVersions: ["retail", "midnight", "forever"],
  },
  {
    id: "src_blizzard_classic_game_data_api",
    category: "Arquitetura & API",
    idType: "Blizzard_Classic_REST_API",
    title: "Blizzard Battle.net WoW Classic Game Data APIs",
    url: "https://community.developer.battle.net/documentation/world-of-warcraft-classic/game-data-apis",
    description: "APIs oficiais de esquemas de dados da Blizzard para World of Warcraft Classic e Classic Era (Itens clássicos, árvores de talentos e reinos).",
    targetVersions: ["forever", "classic_era"],
  },
  {
    id: "src_blizzard_classic_profile_api",
    category: "Arquitetura & API",
    idType: "Blizzard_Classic_Profile_API",
    title: "Blizzard Battle.net WoW Classic Profile APIs",
    url: "https://community.developer.battle.net/documentation/world-of-warcraft-classic/profile-apis",
    description: "APIs oficiais de perfil de personagens no WoW Classic Era e progressão clássica (Armory clássico, equipamentos e reputações).",
    targetVersions: ["forever", "classic_era"],
  },
  {
    id: "src_warcraft_wiki_addon",
    category: "Arquitetura & API",
    idType: "Addon_Architecture",
    title: "AddOn (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/AddOn",
    description: "Manual canônico de desenvolvimento de AddOns para WoW: estrutura de pastas, arquivos .toc, SavedVariables e eventos de ciclo de vida.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_warcraft_wiki_lua",
    category: "Arquitetura & API",
    idType: "Lua_Language_Sandbox",
    title: "Lua no World of Warcraft (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/Lua",
    description: "Ambiente e sandbox de execução Lua 5.1 no WoW, funções permitidas, segurança contra taints e execução em combate.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_db2_category",
    category: "Arquitetura & API",
    idType: "DB2_ID_Index",
    title: "Category:DB2_ID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/Category:DB2_ID",
    description: "Enciclopédia mestra com todos os tipos de identificadores armazenados nas tabelas de banco de dados DB2 do cliente do World of Warcraft.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_wow_api",
    category: "Arquitetura & API",
    idType: "API_Functions",
    title: "World of Warcraft API Oficial",
    url: "https://warcraft.wiki.gg/wiki/World_of_Warcraft_API",
    description: "Documentação completa de todas as funções Lua expostas pelo motor do WoW (namespaces C_* e globais).",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_framexml",
    category: "Arquitetura & API",
    idType: "UI_Engine",
    title: "FrameXML Architecture",
    url: "https://warcraft.wiki.gg/wiki/FrameXML",
    description: "Estrutura do subsistema de interface gráfica em XML e Lua nativo da Blizzard.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_toc_format",
    category: "Arquitetura & API",
    idType: "TOC_Interface",
    title: "TOC Format & Interface Versions",
    url: "https://warcraft.wiki.gg/wiki/TOC_format#Interface_version",
    description: "Mapeamento rigoroso de números de versão do campo ## Interface: em cada patch (ex: 160000 para Forever, 11506 para Era, 110100/120100 para Retail).",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_wow_ui_source",
    category: "Arquitetura & API",
    idType: "UI_Source_Code",
    title: "Gethe / wow-ui-source",
    url: "https://github.com/Gethe/wow-ui-source",
    description: "Repositório completo e desempacotado do código-fonte da interface de todas as branches da Blizzard.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_api_doc_generated",
    category: "Arquitetura & API",
    idType: "API_Documentation",
    title: "Blizzard APIDocumentationGenerated",
    url: "https://github.com/Gethe/wow-ui-source/tree/live/Interface/AddOns/Blizzard_APIDocumentationGenerated",
    description: "Metadados oficiais gerados internamente pela Blizzard contendo assinaturas completas de funções, estruturas e eventos.",
    targetVersions: ["retail", "midnight", "forever"],
  },
  {
    id: "src_wago_db2_central",
    category: "Arquitetura & API",
    idType: "DB2_Central",
    title: "Wago.tools Central DB2",
    url: "https://wago.tools/db2",
    description: "Navegador interativo de dados binários DB2 de qualquer versão de World of Warcraft.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_wago_forever_root",
    category: "Arquitetura & API",
    idType: "DB2_Forever",
    title: "Wago.tools WoW Forever Build 1.60.1.70009",
    url: "https://wago.tools/db2?build=1.60.1.70009",
    description: "Raiz de tabelas DB2 extraídas diretamente do cliente oficial do WoW Forever Beta build 1.60.1.70009.",
    targetVersions: ["forever"],
  },
  {
    id: "src_townlong_constants",
    category: "Arquitetura & API",
    idType: "FrameXML_Constants",
    title: "Townlong-Yak Constants.lua (Slots & Limits)",
    url: "https://www.townlong-yak.com/framexml/live/Blizzard_FrameXMLBase/Constants.lua#183",
    description: "Constantes canônicas do motor Blizzard para slots de inventário, bolsas e IDs numéricos.",
    targetVersions: ["forever", "classic_era", "retail"],
  },

  // 2. Conquistas (Achievement ID)
  {
    id: "src_achievement_id_wiki",
    category: "Conquistas",
    idType: "AchievementID",
    title: "AchievementID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/AchievementID",
    description: "Especificação do ID de conquista usado pelas APIs GetAchievementInfo() e sistema de progresso.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_wowhead_achievements",
    category: "Conquistas",
    idType: "Achievement_Database",
    title: "Wowhead Character Achievements",
    url: "https://www.wowhead.com/achievements/character-achievements",
    description: "Base de dados pública completa de conquistas com descrições, ícones e recompensas.",
    targetVersions: ["retail", "midnight", "classic_era", "forever"],
  },
  {
    id: "src_wowdb_achievements",
    category: "Conquistas",
    idType: "Achievement_Database",
    title: "WoWDB Achievements",
    url: "https://www.wowdb.com/achievements",
    description: "Banco de dados detalhado de conquistas e critérios de conclusão da Curse/MMO-Champion.",
    targetVersions: ["retail", "classic_era"],
  },
  {
    id: "src_wago_db2_achievement",
    category: "Conquistas",
    idType: "AchievementID",
    title: "Wago DB2: Achievement",
    url: "https://wago.tools/db2/Achievement",
    db2Table: "Achievement.db2",
    description: "Tabela DB2 binária de conquistas (ID, título, pontos, categoria, ícone).",
    targetVersions: ["retail", "classic_era"],
  },
  {
    id: "src_wago_db2_achievement_cat",
    category: "Conquistas",
    idType: "AchievementCategory",
    title: "Wago DB2: Achievement_Category",
    url: "https://wago.tools/db2/Achievement_Category",
    db2Table: "Achievement_Category.db2",
    description: "Hierarquia de categorias e seções do painel de conquistas.",
    targetVersions: ["retail", "classic_era"],
  },
  {
    id: "src_wago_forever_achievement",
    category: "Conquistas",
    idType: "AchievementID",
    title: "Wago DB2: Achievement (WoW Forever Build 1.60.1)",
    url: "https://wago.tools/db2/Achievement?build=1.60.1.70009",
    db2Table: "Achievement.db2",
    description: "Conquistas nativas e customizadas do WoW Forever Vanilla+.",
    targetVersions: ["forever"],
  },

  // 3. Itens, Display IDs, Transmogs & Encantamentos
  {
    id: "src_wago_forever_item",
    category: "Itens & Transmog",
    idType: "ItemID",
    title: "Wago DB2: Item (WoW Forever Build 1.60.1)",
    url: "https://wago.tools/db2/Item?build=1.60.1.70009",
    db2Table: "Item.db2",
    description: "Todos os Item IDs clássicos e Vanilla+ do WoW Forever.",
    targetVersions: ["forever"],
  },
  {
    id: "src_wago_forever_item_appearance",
    category: "Itens & Transmog",
    idType: "ItemAppearanceID",
    title: "Wago DB2: ItemAppearance (WoW Forever Build 1.60.1)",
    url: "https://wago.tools/db2/ItemAppearance?build=1.60.1.70009",
    db2Table: "ItemAppearance.db2",
    description: "Vínculos entre modelos 3D (ItemAppearanceID) e equipamentos no WoW Forever.",
    targetVersions: ["forever"],
  },
  {
    id: "src_wowtools_item_mod_appearance",
    category: "Itens & Transmog",
    idType: "ItemModifiedAppearanceID",
    title: "WoW.tools DB2: ItemModifiedAppearance",
    url: "https://wow.tools/dbc/?dbc=itemmodifiedappearance.db2",
    db2Table: "ItemModifiedAppearance.db2",
    description: "Tabela crítica que vincula Item ID, Variação de Cor, Slot e ItemAppearanceID para renderização 3D.",
    targetVersions: ["retail", "midnight", "classic_era", "forever"],
  },
  {
    id: "src_appearance_id_wiki",
    category: "Itens & Transmog",
    idType: "AppearanceID",
    title: "AppearanceID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/AppearanceID",
    description: "Identificador de aparência visual de transmog no guarda-roupa.",
    targetVersions: ["retail", "classic_era", "forever"],
  },
  {
    id: "src_artifact_appearance_id",
    category: "Itens & Transmog",
    idType: "ArtifactAppearanceID",
    title: "ArtifactAppearanceID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/ArtifactAppearanceID",
    description: "Identificadores de aparências das armas artefato de Legion.",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_inventory_slot_id",
    category: "Itens & Transmog",
    idType: "InventorySlotID",
    title: "InventorySlotID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/InventorySlotID",
    description: "Mapeamento dos 19 slots equipados de 1 (Cabeça) a 19 (Tabardo).",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_wowtools_slot_strings",
    category: "Itens & Transmog",
    idType: "GlobalStrings_Slot",
    title: "GlobalStrings Slot Search (WoW.tools)",
    url: "https://wow.tools/dbc/?dbc=globalstrings#search=SLOT",
    description: "Tabela de cadeias globais de localização dos slots de itens.",
    targetVersions: ["forever", "classic_era", "retail"],
  },
  {
    id: "src_transmog_set_id_wiki",
    category: "Itens & Transmog",
    idType: "TransmogSetID",
    title: "TransmogSetID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/TransmogSetID",
    description: "Conjuntos completos de transmogrificação (Sets de Raide, PvP e Masmorra).",
    targetVersions: ["retail", "midnight", "forever"],
  },
  {
    id: "src_wowtools_transmog_set",
    category: "Itens & Transmog",
    idType: "TransmogSetID",
    title: "WoW.tools DB2: TransmogSet",
    url: "https://wow.tools/dbc/?dbc=transmogset",
    db2Table: "TransmogSet.db2",
    description: "Tabela estruturada de conjuntos visuais com vínculos para todas as peças.",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_weapon_enchant_id_wiki",
    category: "Itens & Transmog",
    idType: "WeaponEnchantID",
    title: "WeaponEnchantID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/WeaponEnchantID",
    description: "Identificadores de encantamentos e ilusões visuais de armas.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_wowtools_item_visuals",
    category: "Itens & Transmog",
    idType: "ItemVisualID",
    title: "WoW.tools DB2: ItemVisuals",
    url: "https://wow.tools/dbc/?dbc=itemvisuals.db2",
    db2Table: "ItemVisuals.db2",
    description: "Efeitos visuais, brilhos e partículas renderizados sobre armas e armaduras.",
    targetVersions: ["forever", "classic_era", "retail"],
  },
  {
    id: "src_wowtools_spell_enchantment",
    category: "Itens & Transmog",
    idType: "SpellItemEnchantmentID",
    title: "WoW.tools DB2: SpellItemEnchantment",
    url: "https://wow.tools/dbc/?dbc=spellitemenchantment.db2",
    db2Table: "SpellItemEnchantment.db2",
    description: "Propriedades estatísticas e visuais dos encantamentos aplicados a itens.",
    targetVersions: ["forever", "classic_era", "retail"],
  },

  // 4. Criaturas & Modelos 3D (Creature Display ID)
  {
    id: "src_creature_display_id_wiki",
    category: "Criaturas & Modelos 3D",
    idType: "CreatureDisplayID",
    title: "CreatureDisplayID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/CreatureDisplayID",
    description: "Identificador de malha 3D e texturas usado para NPCs, monstros, chefes e mascotes.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_wago_creature_display_info",
    category: "Criaturas & Modelos 3D",
    idType: "CreatureDisplayInfo",
    title: "Wago DB2: CreatureDisplayInfo",
    url: "https://wago.tools/db2/CreatureDisplayInfo",
    db2Table: "CreatureDisplayInfo.db2",
    description: "Tabela binária com escala, modelo .m2, texturas e vínculos de animação.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },

  // 5. Montarias & Equipamento de Montaria (Mount ID)
  {
    id: "src_mount_id_wiki",
    category: "Montarias",
    idType: "MountID",
    title: "MountID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/MountID",
    description: "Identificador da montaria no Mount Journal e sistema de coleção.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_wago_db2_mount",
    category: "Montarias",
    idType: "MountID",
    title: "Wago DB2: Mount",
    url: "https://wago.tools/db2/Mount",
    db2Table: "Mount.db2",
    description: "Tabela completa de montarias (Mount ID, Spell ID, CreatureDisplayInfoID, flags).",
    targetVersions: ["retail", "classic_era"],
  },
  {
    id: "src_wago_forever_mount",
    category: "Montarias",
    idType: "MountID",
    title: "Wago DB2: Mount (WoW Forever Build 1.60.1)",
    url: "https://wago.tools/db2/Mount?build=1.60.1.70009",
    db2Table: "Mount.db2",
    description: "Montarias específicas e adaptadas para o WoW Forever Vanilla+.",
    targetVersions: ["forever"],
  },
  {
    id: "src_mount_equipment_id_wiki",
    category: "Montarias",
    idType: "MountEquipmentID",
    title: "MountEquipmentID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/MountEquipmentID",
    description: "Equipamentos de montaria (andar sobre a água, anti-queda, etc.).",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_wowtools_mount_equipment",
    category: "Montarias",
    idType: "MountEquipmentID",
    title: "WoW.tools DB2: MountEquipment",
    url: "https://wow.tools/dbc/?dbc=mountequipment.db2",
    db2Table: "MountEquipment.db2",
    description: "Tabela DB2 de itens consumíveis de equipamento de montaria.",
    targetVersions: ["retail", "midnight"],
  },

  // 6. Mascotes de Batalha (Battle Pet IDs)
  {
    id: "src_battle_pet_species_id",
    category: "Mascotes & Pets",
    idType: "BattlePetSpeciesID",
    title: "BattlePetSpeciesID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/BattlePetSpeciesID",
    description: "Identificador de espécie no Diário de Mascotes com atributos e habilidades.",
    targetVersions: ["retail", "midnight", "classic_era", "forever"],
  },
  {
    id: "src_battle_pet_type_id",
    category: "Mascotes & Pets",
    idType: "BattlePetTypeID",
    title: "BattlePetTypeID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/BattlePetTypeID",
    description: "Família do mascote (Humanóide, Fera, Voador, Mecânico, etc.).",
    targetVersions: ["retail", "midnight"],
  },

  // 7. Classes, Raças & Especializações (Spec ID)
  {
    id: "src_class_id_wiki",
    category: "Classes & Specs",
    idType: "ClassID",
    title: "ClassID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/ClassID",
    description: "Identificador numérico padrão da classe (1: Guerreiro, 2: Paladino, ..., 13: Evocador).",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_wowtools_chrclasses",
    category: "Classes & Specs",
    idType: "ClassID",
    title: "WoW.tools DB2: ChrClasses",
    url: "https://wow.tools/dbc/?dbc=chrclasses.db2",
    db2Table: "ChrClasses.db2",
    description: "Tabela binária com nomes, cores hexadecimais de classe e papéis.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_race_id_wiki",
    category: "Classes & Specs",
    idType: "RaceID",
    title: "RaceID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/RaceID",
    description: "Identificador numérico da raça do jogador (Humano, Orc, Anão, etc.).",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_spec_id_wiki",
    category: "Classes & Specs",
    idType: "SpecializationID",
    title: "SpecializationID / SpecID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/SpecializationID",
    description: "Identificador numérico único de cada especialização de classe (ex: 250: Sangue, 73: Proteção).",
    targetVersions: ["retail", "midnight", "classic_era", "forever"],
  },
  {
    id: "src_spec_id_short_wiki",
    category: "Classes & Specs",
    idType: "SpecID",
    title: "SpecID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/SpecID",
    description: "Guia alternativo de mapeamento das especializações de talentos.",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_wago_chr_specialization",
    category: "Classes & Specs",
    idType: "ChrSpecialization",
    title: "Wago DB2: ChrSpecialization",
    url: "https://wago.tools/db2/ChrSpecialization",
    db2Table: "ChrSpecialization.db2",
    description: "Tabela binária de especializações com ícones, papel (Tank/Healer/DPS) e atributos primários.",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_wowtools_chr_specialization",
    category: "Classes & Specs",
    idType: "ChrSpecialization",
    title: "WoW.tools DB2: ChrSpecialization",
    url: "https://wow.tools/dbc/?dbc=chrspecialization",
    db2Table: "ChrSpecialization.db2",
    description: "Consulta e exportação da tabela de especializações.",
    targetVersions: ["retail", "midnight"],
  },

  // 8. Moedas (Currency ID) & Loja de Conta
  {
    id: "src_currency_id_wiki",
    category: "Moedas & Loja",
    idType: "CurrencyID",
    title: "CurrencyID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/CurrencyID",
    description: "Identificador das moedas exibidas na aba Moedas (Emblemas, Pontos de Conquista, etc.).",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_wago_currency_types",
    category: "Moedas & Loja",
    idType: "CurrencyTypes",
    title: "Wago DB2: CurrencyTypes",
    url: "https://wago.tools/db2/CurrencyTypes",
    db2Table: "CurrencyTypes.db2",
    description: "Tabela com limite máximo diário/semanal, ícone e categoria da moeda.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_wago_account_store_cat",
    category: "Moedas & Loja",
    idType: "AccountStoreCategory",
    title: "Wago DB2: AccountStoreCategory",
    url: "https://wago.tools/db2/AccountStoreCategory",
    db2Table: "AccountStoreCategory.db2",
    description: "Categorias da loja de conta e do Posto Comercial (Trading Post).",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_wago_account_store_item",
    category: "Moedas & Loja",
    idType: "AccountStoreItem",
    title: "Wago DB2: AccountStoreItem",
    url: "https://wago.tools/db2/AccountStoreItem",
    db2Table: "AccountStoreItem.db2",
    description: "Itens, montarias e cosméticos do Posto Comercial e loja Blizzard.",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_wago_action_bar_group",
    category: "Moedas & Loja",
    idType: "ActionBarGroup",
    title: "Wago DB2: ActionBarGroup",
    url: "https://wago.tools/db2/ActionBarGroup",
    db2Table: "ActionBarGroup.db2",
    description: "Agrupamento de barras de ação e botões dinâmicos de interface.",
    targetVersions: ["retail", "midnight"],
  },

  // 9. Facções & Reputações
  {
    id: "src_faction_id_wiki",
    category: "Facções & Reputações",
    idType: "FactionID",
    title: "FactionID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/FactionID",
    description: "Identificadores de facções e reputações (Exaltado, Reverenciado, etc.).",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_wago_faction",
    category: "Facções & Reputações",
    idType: "FactionID",
    title: "Wago DB2: Faction",
    url: "https://wago.tools/db2/Faction",
    db2Table: "Faction.db2",
    description: "Tabela binária de facções com nomes, alinhamentos (Aliança/Horda) e índices de reputação.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },

  // 10. Mapas, Zonas, Masmorras & Raides
  {
    id: "src_uimap_id_wiki",
    category: "Mapas & Instâncias",
    idType: "UiMapID",
    title: "UiMapID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/UiMapID",
    description: "Identificador de mapas e zonas usado pela API moderna C_Map.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_wago_uimap",
    category: "Mapas & Instâncias",
    idType: "UiMapID",
    title: "Wago DB2: UiMap",
    url: "https://wago.tools/db2/UiMap",
    db2Table: "UiMap.db2",
    description: "Tabela de mapas hierárquicos (Cosmos, Mundo, Continente, Zona, Subzona).",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_world_map_area_id_wiki",
    category: "Mapas & Instâncias",
    idType: "WorldMapAreaID",
    title: "WorldMapAreaID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/WorldMapAreaID",
    description: "Identificador clássico de áreas do mapa-múndi.",
    targetVersions: ["forever", "classic_era"],
  },
  {
    id: "src_instance_id_wiki",
    category: "Mapas & Instâncias",
    idType: "InstanceID",
    title: "InstanceID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/InstanceID",
    description: "Identificador de masmorras e raides instanciadas.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_wago_map",
    category: "Mapas & Instâncias",
    idType: "MapID",
    title: "Wago DB2: Map",
    url: "https://wago.tools/db2/Map",
    db2Table: "Map.db2",
    description: "Tabela mestra de mapas do motor de jogo (continentes, instâncias, campos de batalha).",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_difficulty_id_wiki",
    category: "Mapas & Instâncias",
    idType: "DifficultyID",
    title: "DifficultyID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/DifficultyID",
    description: "Dificuldades de instâncias (Normal, Heroico, Mítico, Mítico+, 25 Heroico, etc.).",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_dungeon_encounter_id_wiki",
    category: "Mapas & Instâncias",
    idType: "DungeonEncounterID",
    title: "DungeonEncounterID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/DungeonEncounterID",
    description: "Identificador do encontro com chefes em masmorras e raides para rastrear bloqueios e mortes.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_journal_encounter_id_wiki",
    category: "Mapas & Instâncias",
    idType: "JournalEncounterID",
    title: "JournalEncounterID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/JournalEncounterID",
    description: "Identificador do chefe no Almanaque de Masmorras (Adventure Guide).",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_wago_journal_encounter",
    category: "Mapas & Instâncias",
    idType: "JournalEncounter",
    title: "Wago DB2: JournalEncounter",
    url: "https://wago.tools/db2/JournalEncounter",
    db2Table: "JournalEncounter.db2",
    description: "Tabela binária com habilidades, fases e loot de cada encontro do Almanaque.",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_lfg_dungeon_id_wiki",
    category: "Mapas & Instâncias",
    idType: "LfgDungeonID",
    title: "LfgDungeonID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/LfgDungeonID",
    description: "Identificador no Localizador de Masmorras (Dungeon Finder).",
    targetVersions: ["retail", "midnight", "classic_era"],
  },
  {
    id: "src_wago_lfg_dungeons",
    category: "Mapas & Instâncias",
    idType: "LFGDungeons",
    title: "Wago DB2: LFGDungeons",
    url: "https://wago.tools/db2/LFGDungeons",
    db2Table: "LFGDungeons.db2",
    description: "Tabela binária com requisitos de nível, iLvl mínimo e recompensas de fila do LFG.",
    targetVersions: ["retail", "midnight"],
  },

  // 11. Quests, Brinquedos & Profissões
  {
    id: "src_quest_id_wiki",
    category: "Missões & Brinquedos",
    idType: "QuestID",
    title: "QuestID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/QuestID",
    description: "Identificador único de missões (Quests) de Azeroth, requisitos e recompensas.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_toy_id_wiki",
    category: "Missões & Brinquedos",
    idType: "ToyID",
    title: "ToyID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/ToyID",
    description: "Identificador de brinquedos na Caixa de Brinquedos (Toy Box).",
    targetVersions: ["retail", "midnight", "forever"],
  },
  {
    id: "src_wago_toy",
    category: "Missões & Brinquedos",
    idType: "ToyID",
    title: "Wago DB2: Toy",
    url: "https://wago.tools/db2/Toy",
    db2Table: "Toy.db2",
    description: "Tabela binária de brinquedos com vínculos para Item ID e efeitos.",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_tradeskill_line_id_wiki",
    category: "Missões & Brinquedos",
    idType: "TradeSkillLineID",
    title: "TradeSkillLineID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/TradeSkillLineID",
    description: "Identificador de profissões e especializações (Ferraria, Alquimia, Engenharia, etc.).",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_wago_skill_line",
    category: "Missões & Brinquedos",
    idType: "SkillLine",
    title: "Wago DB2: SkillLine",
    url: "https://wago.tools/db2/SkillLine",
    db2Table: "SkillLine.db2",
    description: "Tabela binária de árvores de perícia de profissões e armas.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },

  // 12. Arquivos, Cenas 3D, Filmes, Guarnições & Idiomas
  {
    id: "src_file_data_id_wiki",
    category: "Arquivos & Cenas 3D",
    idType: "FileDataID",
    title: "FileDataID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/FileDataID",
    description: "Identificador numérico universal de arquivos dentro do sistema de arquivos CASC da Blizzard.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_atlas_id_wiki",
    category: "Arquivos & Cenas 3D",
    idType: "AtlasID",
    title: "AtlasID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/AtlasID",
    description: "Texturas empacotadas em atlas de texturas para interface moderna da Blizzard.",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_model_scene_id_wiki",
    category: "Arquivos & Cenas 3D",
    idType: "ModelSceneID",
    title: "ModelSceneID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/ModelSceneID",
    description: "Cenas 3D pré-configuradas com câmera, luz e atores usadas no Armory e no jogo.",
    targetVersions: ["retail", "midnight", "forever"],
  },
  {
    id: "src_marlam_uimodelscene",
    category: "Arquivos & Cenas 3D",
    idType: "UiModelScene",
    title: "Bnet Marlam DB2: UiModelScene",
    url: "https://bnet.marlam.in/dbc.php?dbc=uimodelscene.db2",
    db2Table: "UiModelScene.db2",
    description: "Tabela DB2 de câmeras e cenas para visualizadores 3D de personagens.",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_movie_id_wiki",
    category: "Arquivos & Cenas 3D",
    idType: "MovieID",
    title: "MovieID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/MovieID",
    description: "Identificadores de cinemáticas e vídeos embutidos no cliente.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_wago_movie",
    category: "Arquivos & Cenas 3D",
    idType: "MovieID",
    title: "Wago DB2: Movie",
    url: "https://wago.tools/db2/Movie",
    db2Table: "Movie.db2",
    description: "Tabela binária com resolução, áudio e legendas das cinemáticas.",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_plot_id_wiki",
    category: "Arquivos & Cenas 3D",
    idType: "PlotID",
    title: "PlotID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/PlotID",
    description: "Lotes e terrenos de construção de Guarnições em Warlords of Draenor.",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_building_id_wiki",
    category: "Arquivos & Cenas 3D",
    idType: "BuildingID",
    title: "BuildingID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/BuildingID",
    description: "Edifícios de Guarnição e Salão de Classe (Quartel, Mina, Jardim, Ferraria).",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_contribution_id_wiki",
    category: "Arquivos & Cenas 3D",
    idType: "ContributionID",
    title: "ContributionID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/ContributionID",
    description: "Identificador de contribuição para frentes de guerra e construções mundiais (Costa Partida, etc.).",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_marlam_contribution",
    category: "Arquivos & Cenas 3D",
    idType: "ContributionID",
    title: "Bnet Marlam DB2: Contribution",
    url: "https://bnet.marlam.in/dbc.php?dbc=contribution.db2",
    db2Table: "Contribution.db2",
    description: "Tabela de status e objetivos de construções mundiais de facção.",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_garr_follower_id_wiki",
    category: "Arquivos & Cenas 3D",
    idType: "GarrFollowerID",
    title: "GarrFollowerID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/GarrFollowerID",
    description: "Seguidores e campeões recrutados para missões de mesa de comando.",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_wago_garr_follower",
    category: "Arquivos & Cenas 3D",
    idType: "GarrFollower",
    title: "Wago DB2: GarrFollower",
    url: "https://wago.tools/db2/GarrFollower",
    db2Table: "GarrFollower.db2",
    description: "Tabela de seguidores com qualidade, habilidades e modelos 3D.",
    targetVersions: ["retail", "midnight"],
  },
  {
    id: "src_language_id_wiki",
    category: "Arquivos & Cenas 3D",
    idType: "LanguageID",
    title: "LanguageID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/LanguageID",
    description: "Idiomas do universo (Comum, Órquico, Darnassiano, Tauraceno, Thalassiano, etc.).",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_wago_languages",
    category: "Arquivos & Cenas 3D",
    idType: "LanguageID",
    title: "Wago DB2: Languages",
    url: "https://wago.tools/db2/Languages",
    db2Table: "Languages.db2",
    description: "Tabela binária com algoritmos de cifragem de fala no chat por facção e raça.",
    targetVersions: ["forever", "classic_era", "retail", "midnight"],
  },
  {
    id: "src_ui_widget_set_id_wiki",
    category: "Arquivos & Cenas 3D",
    idType: "UiWidgetSetID",
    title: "UiWidgetSetID (Warcraft Wiki)",
    url: "https://warcraft.wiki.gg/wiki/UiWidgetSetID",
    description: "Conjunto de widgets dinâmicos de interface para objetivos de zona e eventos mundiais.",
    targetVersions: ["retail", "midnight"],
  },
];
